### PR TITLE
Update to fc39

### PR DESCRIPTION
**Pull request by rleon**

### CODE REVIEW

**Comment by kloczek** [comment]
Just tested this PR with 49.0 and build fails.
Just in case I'm using cython 3.0.5
<details>

```console
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/cq.c:7738:18: error: redefinition of ‘__Pyx_Enum_ibv_wc_status_to_py’
 7738 | static PyObject *__Pyx_Enum_ibv_wc_status_to_py(enum ibv_wc_status __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/cq.c:5817:18: note: previous definition of ‘__Pyx_Enum_ibv_wc_status_to_py’ with type ‘PyObject *(enum ibv_wc_status)’ {aka ‘struct _object *(enum ibv_wc_status)’}
 5817 | static PyObject *__Pyx_Enum_ibv_wc_status_to_py(enum ibv_wc_status __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/cq.c:5817:18: warning: ‘__Pyx_Enum_ibv_wc_status_to_py’ defined but not used [-Wunused-function]
make[2]: *** [pyverbs/CMakeFiles/cq.cpython-38-x86_64-linux-gnu.dir/build.make:83: pyverbs/CMakeFiles/cq.cpython-38-x86_64-linux-gnu.dir/cq.c.o] Error 1
make[2]: Target 'pyverbs/CMakeFiles/cq.cpython-38-x86_64-linux-gnu.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:6517: pyverbs/CMakeFiles/cq.cpython-38-x86_64-linux-gnu.dir/all] Error 2
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/device.c:14742:18: error: redefinition of ‘__Pyx_Enum_ibv_event_type_to_py’
14742 | static PyObject *__Pyx_Enum_ibv_event_type_to_py(enum ibv_event_type __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/device.c:10913:18: note: previous definition of ‘__Pyx_Enum_ibv_event_type_to_py’ with type ‘PyObject *(enum ibv_event_type)’ {aka ‘struct _object *(enum ibv_event_type)’}
10913 | static PyObject *__Pyx_Enum_ibv_event_type_to_py(enum ibv_event_type __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/device.c:10913:18: warning: ‘__Pyx_Enum_ibv_event_type_to_py’ defined but not used [-Wunused-function]
make[2]: *** [pyverbs/CMakeFiles/device.cpython-38-x86_64-linux-gnu.dir/build.make:83: pyverbs/CMakeFiles/device.cpython-38-x86_64-linux-gnu.dir/device.c.o] Error 1
make[2]: Target 'pyverbs/CMakeFiles/device.cpython-38-x86_64-linux-gnu.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:6546: pyverbs/CMakeFiles/device.cpython-38-x86_64-linux-gnu.dir/all] Error 2
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/qp.c:8875:18: error: redefinition of ‘__Pyx_Enum_ibv_qp_type_to_py’
 8875 | static PyObject *__Pyx_Enum_ibv_qp_type_to_py(enum ibv_qp_type __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/qp.c:7462:18: note: previous definition of ‘__Pyx_Enum_ibv_qp_type_to_py’ with type ‘PyObject *(enum ibv_qp_type)’ {aka ‘struct _object *(enum ibv_qp_type)’}
 7462 | static PyObject *__Pyx_Enum_ibv_qp_type_to_py(enum ibv_qp_type __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/qp.c:9357:18: error: redefinition of ‘__Pyx_Enum_ibv_qp_state_to_py’
 9357 | static PyObject *__Pyx_Enum_ibv_qp_state_to_py(enum ibv_qp_state __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/qp.c:7944:18: note: previous definition of ‘__Pyx_Enum_ibv_qp_state_to_py’ with type ‘PyObject *(enum ibv_qp_state)’ {aka ‘struct _object *(enum ibv_qp_state)’}
 7944 | static PyObject *__Pyx_Enum_ibv_qp_state_to_py(enum ibv_qp_state __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/qp.c:9872:18: error: redefinition of ‘__Pyx_Enum_ibv_mtu_to_py’
 9872 | static PyObject *__Pyx_Enum_ibv_mtu_to_py(enum ibv_mtu __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/qp.c:8459:18: note: previous definition of ‘__Pyx_Enum_ibv_mtu_to_py’ with type ‘PyObject *(enum ibv_mtu)’ {aka ‘struct _object *(enum ibv_mtu)’}
 8459 | static PyObject *__Pyx_Enum_ibv_mtu_to_py(enum ibv_mtu __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/qp.c:8459:18: warning: ‘__Pyx_Enum_ibv_mtu_to_py’ defined but not used [-Wunused-function]
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/qp.c:7944:18: warning: ‘__Pyx_Enum_ibv_qp_state_to_py’ defined but not used [-Wunused-function]
 7944 | static PyObject *__Pyx_Enum_ibv_qp_state_to_py(enum ibv_qp_state __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/qp.c:7462:18: warning: ‘__Pyx_Enum_ibv_qp_type_to_py’ defined but not used [-Wunused-function]
 7462 | static PyObject *__Pyx_Enum_ibv_qp_type_to_py(enum ibv_qp_type __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [pyverbs/CMakeFiles/qp.cpython-38-x86_64-linux-gnu.dir/build.make:83: pyverbs/CMakeFiles/qp.cpython-38-x86_64-linux-gnu.dir/qp.c.o] Error 1
make[2]: Target 'pyverbs/CMakeFiles/qp.cpython-38-x86_64-linux-gnu.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:6807: pyverbs/CMakeFiles/qp.cpython-38-x86_64-linux-gnu.dir/all] Error 2
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/srq.c:5583:18: error: redefinition of ‘__Pyx_Enum_ibv_ops_wr_opcode_to_py’
 5583 | static PyObject *__Pyx_Enum_ibv_ops_wr_opcode_to_py(enum ibv_ops_wr_opcode __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/srq.c:4566:18: note: previous definition of ‘__Pyx_Enum_ibv_ops_wr_opcode_to_py’ with type ‘PyObject *(enum ibv_ops_wr_opcode)’ {aka ‘struct _object *(enum ibv_ops_wr_opcode)’}
 4566 | static PyObject *__Pyx_Enum_ibv_ops_wr_opcode_to_py(enum ibv_ops_wr_opcode __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/srq.c:4566:18: warning: ‘__Pyx_Enum_ibv_ops_wr_opcode_to_py’ defined but not used [-Wunused-function]
make[2]: *** [pyverbs/CMakeFiles/srq.cpython-38-x86_64-linux-gnu.dir/build.make:83: pyverbs/CMakeFiles/srq.cpython-38-x86_64-linux-gnu.dir/srq.c.o] Error 1
make[2]: Target 'pyverbs/CMakeFiles/srq.cpython-38-x86_64-linux-gnu.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:6865: pyverbs/CMakeFiles/srq.cpython-38-x86_64-linux-gnu.dir/all] Error 2
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/wq.c:4828:18: error: redefinition of ‘__Pyx_Enum_ibv_wq_type_to_py’
 4828 | static PyObject *__Pyx_Enum_ibv_wq_type_to_py(enum ibv_wq_type __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/wq.c:4544:18: note: previous definition of ‘__Pyx_Enum_ibv_wq_type_to_py’ with type ‘PyObject *(enum ibv_wq_type)’ {aka ‘struct _object *(enum ibv_wq_type)’}
 4544 | static PyObject *__Pyx_Enum_ibv_wq_type_to_py(enum ibv_wq_type __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/wq.c:4544:18: warning: ‘__Pyx_Enum_ibv_wq_type_to_py’ defined but not used [-Wunused-function]
make[2]: *** [pyverbs/CMakeFiles/wq.cpython-38-x86_64-linux-gnu.dir/build.make:83: pyverbs/CMakeFiles/wq.cpython-38-x86_64-linux-gnu.dir/wq.c.o] Error 1
make[2]: Target 'pyverbs/CMakeFiles/wq.cpython-38-x86_64-linux-gnu.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:6894: pyverbs/CMakeFiles/wq.cpython-38-x86_64-linux-gnu.dir/all] Error 2
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/wr.c:5218:18: error: redefinition of ‘__Pyx_Enum_ibv_wr_opcode_to_py’
 5218 | static PyObject *__Pyx_Enum_ibv_wr_opcode_to_py(enum ibv_wr_opcode __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/wr.c:4122:18: note: previous definition of ‘__Pyx_Enum_ibv_wr_opcode_to_py’ with type ‘PyObject *(enum ibv_wr_opcode)’ {aka ‘struct _object *(enum ibv_wr_opcode)’}
 4122 | static PyObject *__Pyx_Enum_ibv_wr_opcode_to_py(enum ibv_wr_opcode __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/wr.c:4122:18: warning: ‘__Pyx_Enum_ibv_wr_opcode_to_py’ defined but not used [-Wunused-function]
make[2]: *** [pyverbs/CMakeFiles/wr.cpython-38-x86_64-linux-gnu.dir/build.make:83: pyverbs/CMakeFiles/wr.cpython-38-x86_64-linux-gnu.dir/wr.c.o] Error 1
make[2]: Target 'pyverbs/CMakeFiles/wr.cpython-38-x86_64-linux-gnu.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/Makefile2:6923: pyverbs/CMakeFiles/wr.cpython-38-x86_64-linux-gnu.dir/all] Error 2
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/providers/mlx5/mlx5dv.c:11173:18: error: redefinition of ‘__Pyx_Enum_mlx5dv_dc_type_to_py’
11173 | static PyObject *__Pyx_Enum_mlx5dv_dc_type_to_py(enum mlx5dv_dc_type __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/providers/mlx5/mlx5dv.c:10515:18: note: previous definition of ‘__Pyx_Enum_mlx5dv_dc_type_to_py’ with type ‘PyObject *(enum mlx5dv_dc_type)’ {aka ‘struct _object *(enum mlx5dv_dc_type)’}
10515 | static PyObject *__Pyx_Enum_mlx5dv_dc_type_to_py(enum mlx5dv_dc_type __pyx_v_c_val) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tkloczko/rpmbuild/BUILD/rdma-core-49.0/x86_64-redhat-linux-gnu/pyverbs/providers/mlx5/mlx5dv.c:10515:18: warning: ‘__Pyx_Enum_mlx5dv_dc_type_to_py’ defined but not used [-Wunused-function]
```
</details>

BTW it would be really good to enable issue tracker here to have better visibility of already identified issues.

**Comment by rleon** [comment]
It fails with cython 3.0.2 too

**Comment by EdwardSro** [comment]
They made major changes in Cython 3, (reproducible on any 3.0.0+) I followed the migration guide (from Cython 2
to 3) but did not find anything relevant.
It looks like the new "cythonization" is producing a C code that contains duplicate enum definitions due to the "include <some_enums.pxd>" lines.
I saw similar issues opened (and fixed) on Cython github. Will investigate and update.

**Comment by kloczek** [comment]
> It looks like the new "cythonization" is producing a C code that contains duplicate enum definitions due to the "include <some_enums.pxd>" lines.

Are you sure that duch issue still is preset in recent `cython` 3.0.5? 🤔

**Comment by EdwardSro** [comment]
> Are you sure that duch issue still is preset in recent `cython` 3.0.5? 🤔

Unfortunately yes :( - and it's the latest release (it should contain some fixes that I saw)

**Comment by kloczek** [comment]
> Unfortunately yes :( - and it's the latest release (it should contain some fixes that I saw)

May you drop some links to tickets? 🤔

**Comment by EdwardSro** [comment]
> May you drop some links to tickets? 🤔
Here are a few examples:
https://github.com/cython/cython/issues/5623
https://github.com/cython/cython/issues/5305 (rdma-core package impact is mentioned there)
https://github.com/cython/cython/issues/4308

**Comment by kloczek** [comment]
These are old ticked already closed/resolved.

**Comment by EdwardSro** [comment]
> These are old ticked already closed/resolved.

Yes I know, what I meant is that 3.0.5 already includes some fixes, but it still doesn't fix this issue.
I opened a new ticket.

**Comment by EdwardSro** [comment]
Updated PR: #1419

**Pull request closed without merging**
