### PR TITLE
efa: Fix create QP command over ioctl interface

### PR DESCRIPTION
**Pull request by galpress**
The provider should not access the 'ibv_resp' parts of the response
structure, use the max_inline_data in ibv_qp_init_attr_ex instead.

This issue can be observed when using the ioctl interface for the
create/destroy QP verbs, which keeps the 'ibv_resp' part of the response
cleared.

Suggested-by: Jason Gunthorpe <jgg@ziepe.ca>
Signed-off-by: Gal Pressman <galpress@amazon.com>

### CODE REVIEW

**Comment by rleon** [comment]
Please add Fixes line and add stable@ so @nmorey will be able to pick it to stables too.

Thanks

**Comment by galpress** [comment]
Done

**Comment by rleon** [comment]
@nmorey can you please pick this patch to the stable@?

Thanks

**Comment by rleon** [comment]
> @rleon Picked for v24 -> v29
> 
> As long as stuff is properly tagged with 'Fixes' it'll get picked almost automatically by git-maintain.

Good to know.
Thanks

**Pull request merged**
