### PR TITLE
tests: Extend mlx5 dr steering

### PR DESCRIPTION
**Pull request by EdwardSro**
The series mainly adds multiple mlx5 dr steering tests and extend some of the current tests to run over root tables.

### CODE REVIEW

**Comment by nmorey** [comment]
Commit 1809d847e7d026ca90694a91207b8415258a91ec references a sha1 that does not exists in its Fixes tag.
I found the right one but could we tune the CI scripts to check for that?
Do we have something auto checking patches content already?

**Comment by rleon** [comment]
I was under assumption that checkpatch checks.
Tried it now in the kernel.

➜  kernel git:(tmp) ./scripts/checkpatch.pl /tmp/0001-tmp.patch 
WARNING: Unknown commit id '283b5cc943dc', maybe rebased or not pulled?
#7: 
Fixes: 283b5cc943dc ("RDMA/mlx: remove a lot of unnecessary NULL values")

total: 0 errors, 1 warnings, 8 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

/tmp/0001-tmp.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

**Comment by nmorey** [comment]
It does detect it/
```
SYSTEM_PULLREQUEST_TARGETBRANCH="$(git rev-parse HEAD)" SYSTEM_PULLREQUEST_SOURCECOMMITID="2d31ff99e1c7fbba11a0334622fee530850a6803" ./buildlib/azp-checkpatch  
0001-pyverbs-Fix-typo-in-DrActionFlowSample-creation.patch:8: WARNING: Unknown commit id '5a2a347d547c', maybe rebased or not pulled?
#8: 
Fixes: 5a2a347d547c ("pyverbs: Add dr-action flow sampler support")

##vso[task.logissue type=warning]Unknown commit id '5a2a347d547c', maybe rebased or not pulled?
##vso[task.complete result=SucceededWithIssues]]azp-checkpatch

```
but it's just a warning so it gets ignored

**Comment by rleon** [comment]
Someone needs to change logic in buildlib/azp-checkpatch to treat this warning as error :)

**Pull request merged**
