### PR TITLE
efa: Remove reimplementation of field_avail macro

### PR DESCRIPTION
**Pull request by galpress**
Remove field_avail macro and use the existing vext_field_avail.

Signed-off-by: Gal Pressman <galpress@amazon.com>

### CODE REVIEW

**Comment by rleon** [comment]
Gal, see note from Yishai
https://github.com/linux-rdma/rdma-core/pull/546#issuecomment-517191317

It needs to be fixed too.

**Comment by galpress** [comment]
Will fix, should I open a new PR?

**Comment by rleon** [comment]
> Will fix, should I open a new PR?

No, push fix to this PR

**Comment by galpress** [comment]
Done

**Pull request merged**
