### PR TITLE
Libirdma 052021 test

### PR DESCRIPTION
**Pull request by tatyana-en**
Same as Libirdma 052021 PR, but the file irdma-abi.h is added so that AZP tool can run without compilation issues.

### CODE REVIEW

**Comment by jgunthorpe** [comment]
Do not make new pull requests, just force push your updates to the existing one.

**Comment by shirazsaleem** [comment]
Hi Jason - I read your comment on the list and from what I understand, we need to update the original PR #1013 with an extra commit "update kernel headers" that adds the irdma-abi.h. Unfortunately, Tatyana is out till June 7. Shall I just construct a new PR?

**Comment by jgunthorpe** [comment]
Well, it won't be needed until the kernel driver gets sorted out

**Comment by jgunthorpe** [comment]
Replaced with Shiraz's PR

**Pull request closed without merging**
