### PR TITLE
libhns: Support SRQ record doorbell

### PR DESCRIPTION
**Pull request by hginjgerx**
Compared with normal doorbell, using record doorbell can shorten the process of ringing the doorbell and reduce the latency.

During SRQ creation, the kernel driver will allocate doorbell buffer and notify userspace whether the SRQ record doorbell is enabled with the flag HNS_ROCE_RSP_SRQ_CAP_RECORD_DB. The userspace driver will decide whether to use record doorbell or normal doorbell based on this flag in post SRQ recv process.

This patch relies on the corresponding kernel patch: RDMA/hns: Support SRQ record doorbell

### CODE REVIEW

**Comment by hginjgerx** [comment]
Hi, @jgunthorpe @rleon 
the kernel patch has been applied. Would you please review this PR again?

**Comment by rleon** [comment]
UAPI headers patch should be prepared with https://github.com/linux-rdma/rdma-core/blob/master/kernel-headers/update script

**Comment by hginjgerx** [comment]
> UAPI headers patch should be prepared with https://github.com/linux-rdma/rdma-core/blob/master/kernel-headers/update script
Done.

**Comment by hginjgerx** [comment]
Hi, @rleon @jgunthorpe 
the uapi header issue has been fixed. Would you please review this PR again?

**Pull request merged**
