### PR TITLE
Bugfixes for hip08 userspace

### PR DESCRIPTION
**Pull request by oulijun**
Here are some fixes for hip08 user driver from reviews and test bug.

### CODE REVIEW

**Comment by rleon** [comment]
You have legitime checkpatch warnings.

**Comment by oulijun** [comment]
Sorry. Maybe it check the last patch in my local branch by travisCI and so it can pass.
I will fix it.

Thanks

**Comment by oulijun** [comment]
Hi, Leon
   I have fixed it. But the travisCI is still fail. I check the log and don't find some errors.

Thanks

**Comment by rleon** [comment]
-- Performing Test HAVE_NO_SPARSE - Failed
Patch from '/home/travis/build/linux-rdma/rdma-core/buildlib/sparse-include/27/netinet-in.h.diff' failed
Patch from '/home/travis/build/linux-rdma/rdma-core/buildlib/sparse-include/25/netinet-in.h.diff' failed
Patch from '/home/travis/build/linux-rdma/rdma-core/buildlib/sparse-include/27/stdlib.h.diff' failed
Unable to apply any patch to 'stdlib.h', tries 1
Traceback (most recent call last):
  File "/home/travis/build/linux-rdma/rdma-core/buildlib/gen-sparse.py", line 159, in <module>
    replace_header(I);
  File "/home/travis/build/linux-rdma/rdma-core/buildlib/gen-sparse.py", line 103, in replace_header
    if apply_patch(find_system_header(args,fn),
  File "/home/travis/build/linux-rdma/rdma-core/buildlib/gen-sparse.py", line 48, in find_system_header
    raise ValueError("Could not find system include directory.");
ValueError: Could not find system include directory.
CMake Error at buildlib/RDMA_Sparse.cmake:28 (message):
  glibc header file patching for sparse failed.  Review include/*.rej and fix
  the rejects, then do
  /home/travis/build/linux-rdma/rdma-core/buildlib/gen-sparse.py -out
  /home/travis/build/linux-rdma/rdma-core/build-sparse/include/ --src
  /home/travis/build/linux-rdma/rdma-core/ --save
Call Stack (most recent call first):
  CMakeLists.txt:188 (RDMA_CheckSparse)
-- Configuring incomplete, errors occurred!
See also "/home/travis/build/linux-rdma/rdma-core/build-sparse/CMakeFiles/CMakeOutput.log".
See also "/home/travis/build/linux-rdma/rdma-core/build-sparse/CMakeFiles/CMakeError.log".
The command "buildlib/travis-build" exited with 1.

**Comment by jgunthorpe** [comment]
This seems like something has gone wrong with that sparse patch I merged..

**Comment by jgunthorpe** [comment]
Rebase and force push to clear the error thanks

**Comment by rleon** [comment]
Please prepare proper PR, it should be based on "master" and should not include commits like this
"Merge remote-tracking branch 'upstream/master'"

**Comment by oulijun** [comment]
Sorry, Maybe it’s the reason for pushing the new patch to my local branch. I will fix it.

**Pull request merged**
