### PR TITLE
mlx5: Report ODP capabilities for DC transport

### PR DESCRIPTION
**Pull request by rleon**
Report ODP capabilities for DC through mlx5dv_query_device.

Signed-off-by: Michael Guralnik <michaelgur@mellanox.com>
Signed-off-by: Yishai Hadas <yishaih@mellanox.com>
Signed-off-by: Leon Romanovsky <leonro@mellanox.com>

### CODE REVIEW

**Comment by rleon** [comment]
I want to repeat it again.
Please DON"T merge code which is not part of official for-next or for-rc.
https://git.kernel.org/pub/scm/linux/kernel/git/rdma/rdma.git/log/?h=for-next

ODP DC code is in wip/testing area yet.

Thanks

**Comment by yishaih** [comment]
There is no direct dependency to any kernel series, the driver reads ODP DC caps directly from the device over DEVX.

In any case, the kernel series that turns on the device ODP caps was already accepted by Jason to his for-next branch.

**Comment by rleon** [comment]
> In any case, the kernel series that turns on the device ODP caps was already accepted by Jason to his for-next branch.

There is no Jason's or Doug's for-next, we are working against official for-next and I posted link above.

Thanks

**Comment by yishaih** [comment]
Agree, let's follow that.

Specifically,  this patch has no direct dependency on the kernel series, it uses the DEVX API to read device CAPs, if the kernel will not set them it will just report 0 as expected.

**Pull request merged**
