### PR TITLE
tests: add error flow tests for qp creation

### PR DESCRIPTION
**Pull request by shuki-zanyovka**
Add coverage for the error conditions of QP
creation limits check.

Signed-off-by: Shuki Zanyovka <shukiz@amazon.com>

### CODE REVIEW

**Comment by rleon** [comment]
These fields are FW controlled ones.
They can or can't be equal to 0xFFFFFFFF

**Comment by shuki-zanyovka** [comment]
> 

This is the maximum value possible.
We are trying to simulate an illegal value error to improve the coverage of this test in each of the tests added in this PR.

**Comment by rleon** [comment]
ok, i will rephrase my question.
Will this test pass if my FW sets 0x1 in all these cap fields?
In such case, create_qp() will fail.

**Comment by shuki-zanyovka** [comment]
> ok, i will rephrase my question. Will this test pass if my FW sets 0x1 in all these cap fields? In such case, create_qp() will fail.

In this case:
1) create_qp() will fail.
2) The tests will still pass (see the exception handling per test).

**Comment by rleon** [comment]
[leonro@vm ~]$ ~/src/rdma-core/build/bin/run_tests.py -k create_raw_qp
ssF....ss
======================================================================
FAIL: test_create_raw_qp_ex_with_illegal_caps_max_inline_data (tests.test_qp.QPTest)
Test Raw Packet QP creation via ibv_create_qp_ex with a QPAttr object with illegal max_inline_data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/leonro/src/rdma-core/tests/test_qp.py", line 228, in test_create_raw_qp_ex_with_illegal_caps_max_inline_data
    with self.assertRaises(PyverbsRDMAError) as ex:
AssertionError: PyverbsRDMAError not raised

----------------------------------------------------------------------
Ran 9 tests in 0.113s

I tried it on CX-6 card that in RoCE mode.

**Comment by shuki-zanyovka** [comment]
> 

Hi @rleon ,

I see the issue, looking into a way to improve this.

Thanks,
Shuki

**Comment by shuki-zanyovka** [comment]
Hi @rleon ,

Please see the new commit here, I removed the illegal max_inline_data test completely and added some code to actually query the device for the device capabilities to decide whether or not to run each of the tests.

**Comment by rleon** [comment]
Thanks

**Pull request merged**
