### PR TITLE
ibacm: Support FDR and EDR rates

### PR DESCRIPTION
**Pull request by mattaezell**
Signed-off-by: Matt Ezell <ezellma@ornl.gov>

### CODE REVIEW

**Comment by nmorey** [comment]
Might be worth pushing to stable branches

**Comment by nmorey** [comment]
@jgunthorpe @rleon How do you feel about backporting this kind of "fixes" to the stable branch (and this one in particular)?

IMHO, from a distro PoV, it makes sense to add these patches to older rdma-core releases so that newer HW works well to.
And it's small enough to not cause any problems

**Comment by rleon** [comment]
@nmorey, I have no preference. 

Sorry

**Comment by jgunthorpe** [comment]
I think it is worth backporting this simply because it is pretty much a stealth ABI change. If software starts using these new values it will silently work differently (but not really wrongly) without this patch. Better to have a consistent ABI everywhere??

**Comment by nmorey** [comment]
@jgunthorpe Agreed. Backporting to stable-v15+ branches

**Pull request merged**
