### PR TITLE
Master rdma ndd v2

### PR DESCRIPTION
**Pull request by weiny2**

### CODE REVIEW

**Comment by jgunthorpe** [comment]
Ira, can you just force push this to your other weiny2:master-rdma-nd branch please? Then github does all the comment analysis properly/etc.

I will have to get something to fix udev on travis, probably not till after SC though, sorry.

**Comment by jgunthorpe** [comment]
And we still need a udev rules file for this to be complete.

**Comment by weiny2** [comment]
Ok just force pushed...

**Comment by jgunthorpe** [comment]
I guess Doug closed the old one, in future just force push rather than opening new PRs..

I had time to revise rdma-ndd and complete the packaging and building issues. Please look at:

https://github.com/jgunthorpe/rdma-plumbing/tree/rdma-ndd

If you happy then force push it here (drop the docker commit please). Then send it to the mailing list again - Jarod should check over the RedHat packaging changes.

**Comment by dledford** [comment]
Yeah, I had already closed the other pull request by the time you made the suggestion to force push to it.

**Pull request merged**
