### PR TITLE
srp_daemon fixes

### PR DESCRIPTION
**Pull request by SergeyGorenko**
The patch set includes mix fixes and minor code cleanup for srp_daemon.
The first patch is the most important. It fixes a bug in handling RDMA
device removal. The second patch prevents printing many repeating
messages to the log. The last one removes a couple of lines of unused code.

### CODE REVIEW

**Comment by SergeyGorenko** [comment]
Hi @bvanassche ,

Can you look at this PR?

I cannot add you to Reviewers and do not know whether you receive notifications about a new PR in rdma-core. That's why I'm trying to ping you here. I'm sorry if I'm too impatient.

Thanks,
Sergey

**Review by bvanassche — COMMENTED** [review]
There is a spelling issue in the patch description: I think that pool_cq() should be changed into poll_cq().

**Comment by bvanassche** [comment]
Thanks for mentioning me - without having mentioned me I wouldn't have known about this pull request. The changes look good to me except for one minor spelling issue.

**Comment by SergeyGorenko** [comment]
> There is a spelling issue in the patch description: I think that pool_cq() should be changed into poll_cq().

Thank you for noticing this issue. I just fixed it.

**Pull request merged**
