### PR TITLE
Convert many man pages to markdown format

### PR DESCRIPTION
**Pull request by jgunthorpe**
This converts the .3 man pages in the libibverbs area to markdown format and renders them at compile time into classical *roff files using pandoc.

centos 6 will require an EPEL package to build with pandoc.

### CODE REVIEW

**Comment by jgunthorpe** [comment]
Updated to address mailing list comments:
 - New cmake code to support building without pandoc
 - Only provide uncontroversial .md conversions initially

**Comment by jgunthorpe** [comment]
Updated to fix the travis build failure during RH and SUSE pkg build testing with this:

```diff
diff --git a/buildlib/cbuild b/buildlib/cbuild
index 93ae79f9dfd839..6b6c5878bbd592 100755
--- a/buildlib/cbuild
+++ b/buildlib/cbuild
@@ -439,7 +439,7 @@ def get_image_id(args,image_name):
 
 # -------------------------------------------------------------------------
 
-def get_tar_file(tarfn,pandoc_prebuilt=False):
+def get_tar_file(args,tarfn,pandoc_prebuilt=False):
     """Create a tar file that matches what buildlib/github-release would do if it
     was a tagged release"""
     prefix = "%s-%s/"%(project,get_version());
@@ -454,10 +454,11 @@ def get_tar_file(tarfn,pandoc_prebuilt=False):
     # When the OS does not support pandoc we got through the extra step to
     # build pandoc output in the travis container and include it in the
     # tar. This is similar to what buildlib/github-release does.
-    subprocess.check_call(["buildlib/cbuild","make","travis","docs"]);
+    if not args.use_prebuilt_pandoc:
+        subprocess.check_call(["buildlib/cbuild","make","travis","docs"]);
 
     tmp_tarfn = os.path.join(os.path.dirname(tarfn),"tmp.tar");
-    get_tar_file(tmp_tarfn,False);
+    get_tar_file(args,tmp_tarfn,False);
 
     subprocess.check_call([
         "tar",
@@ -483,7 +484,8 @@ def run_rpm_build(args,spec_file,env):
         os.mkdir(os.path.join(tmpdir,"SOURCES"));
         os.mkdir(os.path.join(tmpdir,"tmp"));
 
-        get_tar_file(os.path.join(tmpdir,"SOURCES",tarfn),pandoc_prebuilt=not env.pandoc);
+        get_tar_file(args,os.path.join(tmpdir,"SOURCES",tarfn),
+                     pandoc_prebuilt=not env.pandoc);
 
         with open(spec_file,"r") as inF:
             spec = list(inF);
@@ -697,6 +699,8 @@ def args_pkg(parser):
     parser.add_argument("ENV",action=ToEnvAction,choices=env_choices());
     parser.add_argument("--run-shell",default=False,action="store_true",
                         help="Instead of running the build, enter a shell");
+    parser.add_argument("--use-prebuilt-pandoc",default=False,action="store_true",
+                        help="Do not rebuild the pandoc cache in build-travis/pandoc-prebuilt/");
 def cmd_pkg(args):
     """Build a package in the given environment."""
     for env in args.ENV:
diff --git a/buildlib/package-build-test b/buildlib/package-build-test
index 15f24caadc6ee8..811009cb45cf07 100755
--- a/buildlib/package-build-test
+++ b/buildlib/package-build-test
@@ -17,5 +17,5 @@ do
        echo "Checking package build for ${OS} ...."
        echo
        buildlib/cbuild build-images ${OS}
-       buildlib/cbuild pkg ${OS}
+       buildlib/cbuild pkg --use-prebuilt-pandoc ${OS}
 done
diff --git a/buildlib/travis-build b/buildlib/travis-build
index cb5c1149a43ab8..02356a3af06724 100755
--- a/buildlib/travis-build
+++ b/buildlib/travis-build
@@ -5,10 +5,10 @@ set -e
 # Echo all commands to Travis log
 set -x
 
-mkdir build-clang build32 build-sparse build-aarch64
+mkdir build-travis build32 build-sparse build-aarch64
 
 # Build with latest clang first
-cd build-clang
+cd build-travis
 CC=clang-5.0 CFLAGS=-Werror cmake -GNinja ..
 ninja
 ../buildlib/check-build --src .. --cc clang-5.0
@@ -38,7 +38,7 @@ fi
 mv ../CMakeLists-orig.txt ../CMakeLists.txt
 
 # Test with coherent DMA mode disabled (ie as would be on ARM32, etc)
-cd ../build-clang
+cd ../build-travis
 cp ../util/udma_barrier.h ../util/udma_barrier.h.old
 echo "#error Fail" >> ../util/udma_barrier.h
 rm CMakeCache.txt
```

**Comment by jgunthorpe** [comment]
@bdrung are we good on this now?

**Comment by bdrung** [comment]
The package builds and no lintian warnings. So from packaging side it looks good. Looked at `ibv_attach_mcast` as example and detected that the SYNOPSIS is not formatted (like the previous man page).

**Comment by bdrung** [comment]
I would avoid the `c` block in the synopsis.

**Comment by jgunthorpe** [comment]
@brung What do you mean 'not formatted'?

Every man page I've looked at uses a .nf region for the synopsis.

We can't drop the .nf or the literal region or it will mess up some of the formatting..

**Pull request merged**
