### PR TITLE
pyverbs: Introducing parent domain

### PR DESCRIPTION
**Pull request by noaos**
Parent domains extend protection domains with custom allocators
callbacks given by the user and override the provider's allocation.

This series adds support for parent domain in pyverbs, including
a basic test and a documentation.

In order to allow Python users to provide Python allocators, pyverbs
is using the pd_context object and an internal wrapper that makes the
Python functions to be called from the provider.

### CODE REVIEW

**Comment by rleon** [comment]
Please rebase

**Comment by noaos** [comment]
PR was rebased and fixed according to Jason's comments from the mail thread.

**Comment by rleon** [comment]
It doesn't pass CI

CMake Error at tests/cmake_install.cmake:81 (file):
  file INSTALL cannot find "/__w/1/s/tests/test_parent_domain".
Call Stack (most recent call first):
  cmake_install.cmake:163 (include)


ABI check skipped, no ABI/ directory.
Traceback (most recent call last):
  File "/__w/1/s/buildlib/check-build", line 511, in <module>
    v(args);
  File "/__w/1/s/buildlib/check-build", line 288, in test_installed_headers
    subprocess.check_output(["ninja","install"],env=env,cwd=args.BUILD);
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', 'install']' returned non-zero exit status 1.
##[error]/usr/bin/python3 failed with return code: 1
##[section]Finishing: Check Build Script

**Comment by noaos** [comment]
Issue was fixed, PR was updated and passes all checks.

**Pull request merged**
