### PR TITLE
suse tweaks

### PR DESCRIPTION
**Pull request by nmorey**
Some minor tuning and fixes on the SUSE spec file
And a change to allow modprobe.d to be moved to /lib instead of /etc

### CODE REVIEW

**Comment by rleon** [comment]
https://dev.azure.com/ucfconsort/rdma-core/_build/results?buildId=39112&view=logs&j=76fe2549-950e-5a54-ed98-09e9602945b4&t=66dc22f5-7ba4-5e20-e598-97f0d58f99fe&l=19

Starting: Perform Package Build
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.198.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash /__w/_temp/e4d81559-ce91-4cdc-bd48-09a28eb9503c.sh
Warning: failed to load Config_git.pl, something strange about this perl...
Warning: failed to load Config_git.pl, something strange about this perl...
Warning: failed to load Config_git.pl, something strange about this perl...
Warning: failed to load Config_git.pl, something strange about this perl...
Warning: failed to load Config_git.pl, something strange about this perl...
Warning: failed to load Config_git.pl, something strange about this perl...
error: Failed build dependencies:
	perl is needed by rdma-core-40.0-0.x86_64

**Comment by nmorey** [comment]
@rleon If I ran cbuild build-images|pkg leap locally it does work
So I'm guessing the container image needs to be updated on azure to match the new cbuild/build requires, but I don't think I have access for that. Could you update the image ?

**Comment by nmorey** [comment]
> @rleon If I ran cbuild build-images|pkg leap locally it does work So I'm guessing the container image needs to be updated on azure to match the new cbuild/build requires, but I don't think I have access for that. Could you update the image ?

I checked and do not have rights there
@jgunthorpe Could you update leap/tumbleweed images with this please?

**Comment by rleon** [comment]
> > @rleon If I ran cbuild build-images|pkg leap locally it does work So I'm guessing the container image needs to be updated on azure to match the new cbuild/build requires, but I don't think I have access for that. Could you update the image ?
> 
> I checked and do not have rights there @jgunthorpe Could you update leap/tumbleweed images with this please?

It didn't work for me too.

**Comment by nmorey** [comment]
It might be worth having a backup here (@rleon probably) in case Jason is unreachable.

**Comment by rleon** [comment]
> It might be worth having a backup here (@rleon probably) in case Jason is unreachable.

You forgot to update azure_pipelines() in build/cbuild.
And you can test locally azp too.

**Comment by nmorey** [comment]
> You forgot to update azure_pipelines() in build/cbuild. And you can test locally azp too.

`cbuild pkg azp` does work.
What fails IIUC is the SUSE build in the azure pipeline because I added a BuildRequires that is satisfied when running build-images locally first but not in CI because images are pre-generated.


It did work with Leap because the rpm RPM does install the minimal required perl-macros. On tumbleweed, it is not the case anymore and the perl package is required for these.
I guess I can tweak my patch to just fix TW but not impact Leap builds

**Comment by jgunthorpe** [comment]
Do you still want an updated tumbleweed in azp? I'm pretty sure leon has permission to do this, but hasn't done it before

**Pull request merged**
