### PR TITLE
cbuild updates to better support opensuse

### PR DESCRIPTION
**Pull request by jgunthorpe**
There were tested by @nmorey 

This can probably be merged after the release.

### CODE REVIEW

**Comment by nmorey** [comment]
I did a little more testing this morning and there's a tiny glitch left.
To be coherent with patch#2, patch#3 must strip the tarfn:
```
diff --git a/buildlib/cbuild b/buildlib/cbuild
index 1fcaab4e..4c3ef36b 100755
--- a/buildlib/cbuild
+++ b/buildlib/cbuild
@@ -457,7 +457,7 @@ os.setuid({uid:d});
 # Get RPM to tell us the expected tar filename.
 for ln in subprocess.check_output(["rpmspec","-P",{tspec_file!r}]).splitlines():
    if ln.startswith("Source:"):
-      tarfn = ln.strip().partition(' ')[2];
+      tarfn = ln.strip().partition(' ')[2].strip();
 os.symlink({tarfn!r},os.path.join("SOURCES",tarfn));
 """.format(passwd=":".join(str(I) for I in pwd.getpwuid(os.getuid())),
            group=":".join(str(I) for I in grp.getgrgid(os.getgid())),
```

BTW, what is the policy between the ML and github ?
Are github PR enough? Should it be posted to the ML ?

**Comment by jgunthorpe** [comment]
PR revised with nmorey's incremental patch.

For tiny revisions like this github is fine, IMHO. Larger things should go through the mailing list..

**Comment by rleon** [comment]
@nmorey - major changes, API, external headers, cross-tree -> ML, small and self descriptive changes -> github is enough.
@jgunthorpe - I think that it can be merged now, there is no need to delay

**Comment by jgunthorpe** [comment]
Merging is fine by me, once nmorey says it is done..

**Comment by nmorey** [comment]
This works for me

**Pull request merged**
