### PR TITLE
Better srp_daemon/libibumad integration

### PR DESCRIPTION
**Pull request by hnrose**
Also, some srp_daemon cleanups

### CODE REVIEW

**Comment by bvanassche** [comment]
These changes trigger the following build error on the two systems I tried to build this code on:

> srp_daemon/srp_handle_traps.c: In function ‘register_to_trap’:
> srp_daemon/srp_handle_traps.c:633:23: error: ‘struct umad_sa_packet’ has no member named ‘mad’
>     if (res->mad_buffer->mad.hdr.base_version == 0)

**Comment by hnrose** [comment]
I fixed that typo. Sorry. Look at latest PR.

**Comment by bvanassche** [comment]
The changes look good to me, and commit bb7cffb504fe works fine on my test setup.

**Comment by hnrose** [comment]
@bvanassche ,
Thanks a lot for checking this out, Bart!

**Pull request merged**
