### PR TITLE
Fix lintian issues: Set upstream metadata fields: Repository, Repository-Browse.

### PR DESCRIPTION
**Pull request by debian-janitor**
Set upstream metadata fields: Repository, Repository-Browse.

This merge proposal was created automatically by the Janitor bot
(https://janitor.debian.net/lintian-fixes).

You can follow up to this merge proposal as you normally would.

Build and test logs for this branch can be found at
https://janitor.debian.net/lintian-fixes/pkg/rdma-core/b0e948bb-bbde-4baa-a912-a10455afd82b.

### CODE REVIEW

**Comment by rleon** [comment]
@bdrung 
I remember that you asked me do not change debian/changelog. This commit changes it.
Is it ok?

**Comment by jelmer** [comment]
The Janitor uses some heuristics to determine whether the changelog is maintained using *gbp dch* or manually. It looks like that didn't work in this case - I've added an override for rdma-core and triggered a rerun, which should update this pull request shortly.

**Comment by rleon** [comment]
@jelmer I don't see an update yet.

Thanks

**Comment by bdrung** [comment]
This change should go into the master branch as well.

**Pull request merged**
