### PR TITLE
Fix typo in pyverbs.md

### PR DESCRIPTION
**Pull request by hauntsaninja**

### CODE REVIEW

**Comment by EdwardSro** [comment]
Please add your signoff to the commit.

**Review by jgunthorpe — CHANGES_REQUESTED** [review]
Must included a signed-off-by

**Comment by hauntsaninja** [comment]
Added a signoff!

**Comment by rleon** [comment]
DCO  checker failed because your SOB and author are different.

From: Shantanu <12621235+hauntsaninja@users.noreply.github.com>
....
Signed-off-by: Shantanu Jain <hauntsaninja@gmail.com>

**Comment by hauntsaninja** [comment]
Changed it to match the Github author

**Comment by rleon** [comment]
> Changed it to match the Github author

I would say that it should be an opposite - you should have real author line and real SOB line.

**Comment by hauntsaninja** [comment]
I have reasons for not wanting to attach my email to all my GitHub commits. Thanks for helping with the contribution process, but this PR is trivial so I'm just going to close this out :-)

**Comment by rleon** [comment]
Thank you for investing time.

**Pull request closed without merging**
