### PR TITLE
minor cleanups

### PR DESCRIPTION
**Pull request by zhijianli88**
Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>

### CODE REVIEW

**Comment by rleon** [comment]
In userspace, application exit causes to memory allocation to be freed, so it doesn't fix any potential memory leaks, but makes code more clean.

Thanks

**Comment by zhijianli88** [comment]
> In userspace, application exit causes to memory allocation to be freed, so it doesn't fix any potential memory leaks, but makes code more clean.

I see, so do you want to pick up such PR ?
Or feel free to close it. :)

**Comment by rleon** [comment]
> > In userspace, application exit causes to memory allocation to be freed, so it doesn't fix any potential memory leaks, but makes code more clean.
> 
> I see, so do you want to pick up such PR ?
> Or feel free to close it. :)

It's upto you.

If you want me to merge the PR, please update commit messages so it won't be empty and won't include "potential leaks".
If you don't want, it is also fine, just say it. :)

**Comment by zhijianli88** [comment]
> > > In userspace, application exit causes to memory allocation to be freed, so it doesn't fix any potential memory leaks, but makes code more clean.
> > 
> > 
> > I see, so do you want to pick up such PR ?
> > Or feel free to close it. :)
> 
> It's upto you.
> 
> If you want me to merge the PR, please update commit messages so it won't be empty and won't include "potential leaks".
> If you don't want, it is also fine, just say it. :)

updated PR description and commt message, PTAL

**Comment by rleon** [comment]
Thanks

**Pull request merged**
