### PR TITLE
systemd hardening

### PR DESCRIPTION
**Pull request by nmorey**
SUSE is launching a system wide effort to harden systemd service files:
See https://en.opensuse.org/openSUSE:Security_Features#Systemd_hardening_effort

### CODE REVIEW

**Comment by nmorey** [comment]
@Honggang-LI  @bdrung @Kamalheib Is this OK with your distros ?
I'd rather avoid having SUSE specific service files if possible (or maintain in-house patches on top)

**Comment by rleon** [comment]
> @Honggang-LI @bdrung @Kamalheib Is this OK with your distros ? I'd rather avoid having SUSE specific service files if possible (or maintain in-house patches on top)

if it isn't possible to use for all distros, we can save these files in suse/* folder.

Thanks

**Comment by nmorey** [comment]
> if it isn't possible to use for all distros, we can save these files in suse/* folder.
> 
> Thanks

Sure. That was my second plan. But if it works for other distros, let's make them all more secure :)

**Comment by Honggang-LI** [comment]
>  Is this OK with your distros ? 

```
ProtectSystem=full
ProtectHome=true
ProtectHostname=true
ProtectKernelLogs=true
```
systemd version required for those?

**Comment by nmorey** [comment]
`ProtectSystem` / `ProtectHome`: 214
`ProtectHostname`: 242
`ProtectKernelLogs`: 244

**Comment by bdrung** [comment]
So Debian 11 (bullseye) and Ubuntu 20.04 (focal) have recent enough systemd versions. Will older systemd version just ignore these setting?

I am totally for sharing these hardening improvements for the general systemd service files. So go for it. I haven't tested the changes yet, but the diff looks good to me.

**Comment by jgunthorpe** [comment]
Centos7 is 219 and is still something in the CI. I think the thing to do is to sed away the unsupported logic when we install the systemd files. Should be easy enough to do in cmake?

**Comment by nmorey** [comment]
> So Debian 11 (bullseye) and Ubuntu 20.04 (focal) have recent enough systemd versions. Will older systemd version just ignore these setting?
> 

Older versions ignore these and outputs a warning somewhere in journalct
`Unknown lvalue 'ProtectKernelLogs' in section 'Service'`

So for CI, it shouldn't be an issue either

**Comment by Honggang-LI** [comment]
It is ok for me to share these hardening improvements for the general systemd service files.

> Older versions ignore these and outputs a warning somewhere in journalct `Unknown lvalue 'ProtectKernelLogs' in section 'Service'`

We had fixed such issue for rdma stack package as required by RHEL user. I think jgunthorpe's suggestion looks good for me.

https://github.com/linux-rdma/rdma-core/pull/1089#issuecomment-975993813

> So for CI, it shouldn't be an issue either

**Pull request merged**
