### PR TITLE
add scripts to build debian format package

### PR DESCRIPTION
**Pull request by iotcg**
Build Steps:
1) git clone https://github.com/linux-rdma/rdma-core.git
2) cd rdma-core
3) bash tools/make-debs.sh

Results:
cd /tmp/release/Ubuntu/

### CODE REVIEW

**Comment by bdrung** [comment]
make-debs.sh does a lot of decisions:
* it strips away debug packages
* it sets the distribution to the running release
* it builds the package locally
* it hardcodes using reprepro

Have you tried using git-buildpackage instead? That would shorten your script.

**Comment by iotcg** [comment]
@bdrung 
If you run the script, you'll find that debug packages is there.
Could you share your method to build the deb packages locally?

Q: Why do I need build the package locally?
A: I'm working on ceph(storage) and need enable RDMA & deploy them on several machines. Get the local build deb format package is more easy for me to do deployment insteading of copying library directly on several machines.

**Comment by bdrung** [comment]
I normally use sbuild to build the package (with schroot environments, with overlaysfs on tmpfs for making the changes disposable). If I want to build a git checkout, I will call `git archive` to create a source tarball. Two commands are not small enough to not need a script.

For deploying stuff in the company, we have a full build chain: a push of to git repository triggers a build and upload to our in-house repository (git webhook → build job → gitpkg for building the source → sbuild for building → dput for uploading → [reprepro with multiple version support](https://github.com/profitbricks/reprepro) → webserver serving the repository).

**Comment by iotcg** [comment]
@bdrung 
Could you show your whole "sbuild" method to finish building out deb format package?
Set up the whole CI chain is luxury for me.

**Comment by bdrung** [comment]
First create schroot environments using [sbuild-createchroot](https://manpages.debian.org/stretch/sbuild/sbuild-createchroot.8.en.html). Then adjust the configuration, e.g. `/etc/schroot/chroot.d/unstable` on my systems contains:
```
[unstable]
description=Debian unstable/amd64 autobuilder
groups=root,sbuild
root-groups=root,sbuild
source-groups=root,sbuild
source-root-groups=root,sbuild
profile=sbuild
type=directory
directory=/srv/chroot/unstable
union-type=overlay
union-overlay-directory=/tmpfs
aliases=sid,default
```
and `/tmpfs` is a tmpfs mount point:
```
tmpfs                         /tmpfs          tmpfs   defaults,size=50%      0       0
```
The I just call `sbuild -d unstable` in the git repository. This way you can have one schroot for each release of Debian and Ubuntu.

**Comment by jgunthorpe** [comment]
I think there are already so many ways to build packages we don't need another in tree.

The official way to build packages in-tree is by using buildlib/cbuild & docker.

**Comment by iotcg** [comment]
@bdrung & @jgunthorpe 
We all give several methods here.
Could you give a simple quick method for building debian package for local development?
Could you help me find what's wrong with my method? The Travis CI build failed.

**Comment by rleon** [comment]
@iotcg 
./buildlib/cbuid build-images ...
./buildlib/cbuid make ...
./buildlib/cbuid pkg ...

**Pull request closed without merging**
