### PR TITLE
SRQ user mode support for hns

### PR DESCRIPTION
**Pull request by oulijun**
This patch series add necessary implements for supporting srq
 features to hip08 user space.

### CODE REVIEW

**Comment by oulijun** [comment]
Need me to resubmit? I have update the kernel-headers/rdma/hns-abi.h in the patchset and build success

**Comment by rleon** [comment]
You need to push with force (-f) to the same branch your new commits.

**Comment by oulijun** [comment]
But I have not made any changes based on the patch series. Still need git push -f？

**Comment by rleon** [comment]
We do expect to see patch generated by kernel-header/update script being first in series.

**Comment by oulijun** [comment]
Hi， leon
  Could I run the script based on the srq_v2 branch for pull reqeust?

**Comment by rleon** [comment]
I don't know what that srq_v2 means.

**Comment by oulijun** [comment]
srq_v2 is a branch of my local rdma-core repository, srq patch is pushed on the branch. The pull-request of srq series is generated based on this branch.

**Comment by yishaih** [comment]
Please sync to master rebase and upload a new series, the kernel-headers files were updated to include the kernel changes till a commit that includes your code.

**Comment by oulijun** [comment]
I always have a question. if the origin/master have updated. I can run the git merge upstream/master to sync. However, I don't update the srq_v2 that it is created based on my fork master branch.  How should
I do it? I need to create a new branch and git push the fixed patch series?

**Comment by rleon** [comment]
The usual development flow is as follows:
1. Create fork from upstream repository
2. Create new branch in your new forked repository
3. Write your patches in that new branch
4. Update your forked repo (git remote update)
5. Switch to master branch and reset it to new HEAD, usually it will be "git reset --hard origin/master"
I assume that "origin" points to upstream repository and not to forked
6. Switch back to your development branch
7. Update this branch by rebase
git rebase --onto master --to the_name_of_this_branch
Fix conflicts if it is needed
8. Create R to main repo
9. If comments received, fix them and return to step #4, but instead of creating PR, do git push -f

Hope that it helps.
Thanks

**Pull request closed without merging**
