### PR TITLE
Ibacm make nmbr ep addr dynamic

### PR DESCRIPTION
**Pull request by Hakon-Bugge**

### CODE REVIEW

**Comment by Hakon-Bugge** [comment]
@jgunthorpe , @dledford Please do not merge. Just found a bug.

**Comment by Hakon-Bugge** [comment]
Please revert this one, as per my comment above. In hindsight, I see that I simply should have closed the PR.

**Comment by rleon** [comment]
reverted

**Comment by Hakon-Bugge** [comment]
@rleon Where do I find the two reverts?

**Comment by rleon** [comment]
I pushed them to wrong remote, it was my private fork and not official rdma-core.
I'm pushing now.

Thanks

**Comment by Hakon-Bugge** [comment]
@Hakon-Bugge has eggs all over his face. My first PR ever using github, #400, was a PR from my master branch. When working on this PR, I had finger-trouble and it incorrectly got pushed to my master branch (in addition to the designated branch). Sigh!

But it is not not as messy at it sounds. We are just missing the three commits from PR #400.  

Will recreate them. Sorry for the inconvenience.

**Comment by jgunthorpe** [comment]
Every pull request should be from a unique branch in your repo, or things tend to go bad.. Delete the branch after the PR is merged.

**Comment by rleon** [comment]
@Hakon-Bugge let's stop to use PR for a while and return to the basics.
Can you send all needed patches to the linux-rdma ML?

Thanks

**Comment by Hakon-Bugge** [comment]
I am following the recipe from @jgunthorpe . I can do either (i.e. ML or PR).

**Pull request merged**
