### PR TITLE
libibumad: Alphabetically sorting CA device list in umad_get_ca_devic…

### PR DESCRIPTION
**Pull request by haimbo**
…e_list API

Implement insertion sort in umad_get_ca_device_list API.
The CA device list will be returned sorted in alphabetical order.

Signed-off-by: Haim Boozaglo <haimbo@mellanox.com>

### CODE REVIEW

**Comment by haimbo** [comment]
After we checked all the options, we decided that this is the best solution
to make sorting when we create the list.

**Comment by jgunthorpe** [comment]
Seriously? The best option is bubble sort?

I still prefer this be a helper function, not built it.

**Comment by rleon** [comment]
> Seriously? The best option is bubble sort?
> 
> I still prefer this be a helper function, not built it.

I said the same (helper function) in some offline discussion too.

Thanks

**Comment by jgunthorpe** [comment]
Replaced by #746

**Pull request closed without merging**
