### PR TITLE
Rsocket fixes

### PR DESCRIPTION
**Pull request by pizhenwei**
Fix several issues for rsocket/rstream in this patch set.

### CODE REVIEW

**Comment by pizhenwei** [comment]
@rleon Hi, I'm trying to use rsocket to support Redis, hit several issues and try to fix them.
I'd like to invite you to review this PR too.
https://github.com/redis/redis/pull/9270

**Comment by rleon** [comment]
I looked on the PR and everything upto "rsocket: make rsocket forkable" looks OK.

The last patch, I would be happy if @shefty review it.

**Comment by rleon** [comment]
> @rleon Hi, I'm trying to use rsocket to support Redis, hit several issues and try to fix them.
> I'd like to invite you to review this PR too.
> [redis/redis#9270](https://github.com/redis/redis/pull/9270)

I don't know redis to help you with review. It is unclear why you chose rsocket.

**Comment by pizhenwei** [comment]
> > @rleon Hi, I'm trying to use rsocket to support Redis, hit several issues and try to fix them.
> > I'd like to invite you to review this PR too.
> > [redis/redis#9270](https://github.com/redis/redis/pull/9270)
> 
> I don't know redis to help you with review. It is unclear why you chose rsocket.

"low level API of verbs for redis" VS "an external module" was discussed in a previous PR[](https://github.com/redis/redis/pull/9161).
Because rsocket is a part of rdma-core, it should be more common and stable(I guest ...), no more dependence(librdmacm is enough).

**Comment by rleon** [comment]
> > > @rleon Hi, I'm trying to use rsocket to support Redis, hit several issues and try to fix them.
> > > I'd like to invite you to review this PR too.
> > > [redis/redis#9270](https://github.com/redis/redis/pull/9270)
> > 
> > 
> > I don't know redis to help you with review. It is unclear why you chose rsocket.
> 
> "low level API of verbs for redis" VS "an external module" was discussed in a previous [PR](https://github.com/redis/redis/pull/9161)
> Because rsocket is a part of rdma-core, it should be more common and stable(I guest ...), no more dependence(librdmacm is enough).

All libraries in the rdma-core provide stable API and libibverbs is not the exception here. 

At the end, rsocket depends on the libibverbs and it can be seen as a wrapper over libibverbs which is definitely not common and almost not supported.

Your first PR was correct (direct use of libibverbs) and you shouldn't listen to random dudes on the internet.

Thanks

**Comment by rleon** [comment]
Let's close this PR till your Redis adventure will be more clear.

Thanks

**Comment by pizhenwei** [comment]
> Let's close this PR till your Redis adventure will be more clear.
> 
> Thanks

I think these bugs still should be fixed. Other guys may also hit crash during test or use rsocket(even not for redis).

**Comment by rleon** [comment]
> > Let's close this PR till your Redis adventure will be more clear.
> > Thanks
> 
> I think these bugs still should be fixed. Other guys may also hit crash during test or use rsocket(even not for redis).

I don't know if anyone in the world uses rsocket :)

**Pull request closed without merging**
