### PR TITLE
Proper command for verbose make

### PR DESCRIPTION
**Pull request by tzafrir-mellanox**
'make -v' is version information.

Signed-off-by: Tzafrir Cohen <mellanox@cohens.org.il>

### CODE REVIEW

**Comment by jgunthorpe** [comment]
We do build on make with these spec files, and rpms seem to come out, what happens/how does it work right now?

Add a fixes line?

**Comment by tzafrir-mellanox** [comment]
Any chance only a build with ninja is tested?

It fixes 8854eefa6 (the commit that added the suse/rdma-core.spec) and 3888efcdf (the commit that added redhat/rdma-core.spec). Should I add two Fixes lines?

**Comment by nmorey** [comment]
> Any chance only a build with ninja is tested?
> 

For SUSE, pretty sure it's a yes. Older distros without ninja are not using rdma-core

**Comment by jgunthorpe** [comment]
Look here:

https://dev.azure.com/ucfconsort/f3b4a7f7-c9a7-467e-8013-95fd10fcc2ac/_apis/build/builds/3717/logs/50

I see that the 'make install' triggers the build automatically.

Please update the commit message and force push

**Pull request merged**
