### PR TITLE
More sparse work for more providers

### PR DESCRIPTION
**Pull request by jgunthorpe**
This does the mellanox providers and vmw_pvrdma

### CODE REVIEW

**Comment by jgunthorpe** [comment]
Revised as per the mailing list, except for the ibv_wc stuff

**Comment by rleon** [comment]
@jgunthorpe  what is our status here?

We are preparing to release and cleaning table before it.

**Comment by jgunthorpe** [comment]
@leon, Everything asked for was done, if you can live with the __force cast it is good to go.

**Comment by jgunthorpe** [comment]
The travis failure is bogus due to the checkpatch stuff.

**Comment by rleon** [comment]
@jgunthorpe, it is not bogus, just rdma-core is not ready for strict checks.

**Comment by rleon** [comment]
@jgunthorpe with force, I can deal, but the _CHECKER_ ifdef in public header is too distracting for me. Can we strip it during creation of packages and tar.gz, so headers will be clean?

**Comment by rleon** [comment]
@jgunthorpe and please post to the mailing list, it is hard to see the differences between versions.

thanks

**Comment by rleon** [comment]
voilà, your pull request is passing again.

**Comment by rleon** [comment]
Thanks

**Pull request merged**
