### PR TITLE
Changes from Debian upload 42.0-1

### PR DESCRIPTION
**Pull request by bdrung**
* Update overrides for lintian 2.115.2
  * Bump Standards-Version to 4.6.1

### CODE REVIEW

**Comment by bdrung** [comment]
The Azure pipelines need to update their lintian version.

**Comment by rleon** [comment]
> 



> The Azure pipelines need to update their lintian version.

It needs to be done in this PR or before it. I can't merge code that fails.

Thanks

**Comment by bdrung** [comment]
I didn't find a way to (easily) configure that in `buildlib/azure-pipelines.yml`. The new lintian version is only in Debian for now. Soon it will be in Ubuntu, but in Ubuntu >= 22.10.

**Comment by jgunthorpe** [comment]
This is really obnoxious that lintian needs upgrading - this has never happened before, can we avoid it somehow?

**Comment by bdrung** [comment]
The lintian output should not change too often and therefore the override won't need adjustments. To align with the Debian package in Debian, lintian from testing or unstable should be used. So can the pipeline run the lintian test inside a Debian testing/unstable container?

**Comment by jgunthorpe** [comment]
I mean, why can't we have an override that is the union of what debian testing and ubuntu can use?

Adding more containers is difficultish, and keeping something rolling like debian testing up to date is not so practical.

We could try to squeeze an updated lintian into the azp container, but that seems hard and maybe not really worth it?

We could also drop the lintian tests from the CI?

I'm not sure?

**Comment by rleon** [comment]
Closed due to missing activity

**Pull request closed without merging**
