### PR TITLE
cxgb4: Add support for 64Byte cqes

### PR DESCRIPTION
**Pull request by rajrangoju**
This series adds support for user-space cxgb4 to extend cqe from existing 32Byte size to 64Byte.

### CODE REVIEW

**Comment by larrystevenwise** [comment]
Looks like formatting errors.  @jgunthorpe What is the process for resubmitting the PR?  Thanks!

**Comment by jgunthorpe** [comment]
@larrystevenwise 'git push -f' the branches 

You should use buildlib/cbuild pkg travis locally to make sure everything is OK. Requires docker to be installed.

**Comment by larrystevenwise** [comment]
Hey @jgunthorpe - The kernel patch was posted: https://www.spinics.net/lists/linux-rdma/msg66771.html
What do we need to do to resolve the needs-kernel-patch tag?

**Comment by jgunthorpe** [comment]
@larrystevenwise The patch needs to be applied to the rdma for-next git tree to loose the tag..

**Comment by rajrangoju** [comment]
@jgunthorpe formatting errors were fixed. All checks have passed.

**Comment by rajrangoju** [comment]
Hi @jgunthorpe, the kernel patches for srq support were posted  at
https://www.spinics.net/lists/linux-rdma/msg66999.html
https://www.spinics.net/lists/linux-rdma/msg67000.html
https://www.spinics.net/lists/linux-rdma/msg67001.html

**Comment by rleon** [comment]
1. Please clean subject lines of patches, there is no need to write "rdma-core" while pushing to rdma-core.
2. Only after kernel part will be accepted, we will take it with proper (official) "updated kernel headers" patch

**Comment by rajrangoju** [comment]
Thanks @rleon. I have cleaned the subject lines of the patches.
Links to the kernel patches (cqe and srq) were in the above comments.

**Comment by jgunthorpe** [comment]
Update with revised kernel headers and just the cqe 64 patch

Raju, you should send pull requests from a branch other than master on your github.

You will also need to open a new PR for the SRQ feature.

**Comment by larrystevenwise** [comment]
@jgunthorpe - does raju need to wait on the srq pr until you merge the cqe commits and close this pr?  Otherwise, it seems like when he creates the srq pr, it would again pull in the cqe commits.  I guess the question is how to manage concurrent prs where pr2 depens on pr1.

**Comment by jgunthorpe** [comment]
You can push the SRQ commits on top of these commits to their own branch and github works it out. At worst SRQ would have to be trivially rebased, no problem.

**Comment by jgunthorpe** [comment]
Well, now we have two 64b pull requests.. You need to make one of these into the SRQ one

**Comment by rajrangoju** [comment]
Changed #360 to SRQ

**Pull request merged**
