### PR TITLE
redhat: Do not add rdma-ndd to initramfs

### PR DESCRIPTION
**Pull request by pjgeorg**
See #985 for further details.

### CODE REVIEW

**Comment by Honggang-LI** [comment]
Looks good for me. Thanks

**Comment by rleon** [comment]
Please add Fixes line and all the needed details into the commit message. The change should be explained sufficient enough to understand without looking on github webpage.

**Comment by pjgeorg** [comment]
Added further information to the commit message as requested.

**Comment by rleon** [comment]
Thanks

**Comment by nmorey** [comment]
The commit does not have the proper Fixes: tag 

@pjgeorg  What Leon and I mean when talking about Fixes line/tag is something like this:
`Fixes: 8bb38f6cb1b2 (redhat: update dracut setting)`
See 3166f3f3d557c6053a826830066993d50564e929 for example.

This tag can be used by tools to detect when and where patches need to be backported among other things.
With such a tag, my tool would have picked up your fix to be applied almost automatically.
In your case, I did see the github chat and will do it manually.

**Comment by pjgeorg** [comment]
@nmorey Sorry, I didn't know about this particular form of Fixes line/tag. Seems like either none of the open source projects I contributed to so far (just a few) used this format or no one ever bothered to tell me.
Thanks for informing me about this workflow and sorry for any inconveniences caused.

**Comment by rleon** [comment]
It's ok, we are not so picky for one time contributors :)

**Pull request merged**
