### PR TITLE
srp_daemon fixes

### PR DESCRIPTION
**Pull request by nmorey**
This patch series fixes two issues of srp_daemon which occur when the master SM switches.
Both causes a failure to register to SM traps.

### CODE REVIEW

**Comment by nmorey** [comment]
@rleon  Can we get this one in ?

**Comment by rleon** [comment]
What did you decide about  "stable versions"?
Why isn't enough to write #v14 so all versions after it will get it?

**Comment by nmorey** [comment]
@rleon agreed. Do you want me to resubmit for this ? Or let's agree to just put the oldest version after this PR ;)

**Comment by rleon** [comment]
better to repush, people will copy/paste :)

**Comment by nmorey** [comment]
Updated :)

**Comment by rleon** [comment]
Thanks, LIFO :)

**Pull request merged**
